#!/bin/bash
# ----------------------------------------------------------
#title                  :check_Getlocation_API
#description     :This script is used to check for Locus IR API directly to Locus-IR platform  
#author             :Jason Wang 
#email               :jw7698@att.com
#date                 :20140923
#version            :0.1
#usage               :check_Getlocation_API (returns either exit 0 or 2)
#notes               :Intended to be in /usr/lib/nagios/plugins on Locus-IR loadbalance server 
# ----------------------------------------------------------

#Get location API call  
#On luir-prod-lb1-sql1 
status=`curl -silent -k -H 'Authorization:Basic YmxhY2tmbGFnLXByb2Q6bDBjdTVSMGFtIU42' "https://192.168.1.25:8087/locus-ir/locus/ir/roaming/location/swc_1169831652275_0098_1900297383_vmag.mycingular.net" | grep HTTP | awk '{print $2}'`

#On luir-prod-lb2-sql1 
status=`curl -silent -k -H 'Authorization:Basic YmxhY2tmbGFnLXByb2Q6bDBjdTVSMGFtIU42' "https://192.168.1.6:8087/locus-ir/locus/ir/roaming/location/swc_1169831652275_0098_1900297383_vmag.mycingular.net" | grep HTTP | awk '{print $2}'`


#If the HTTP status check not equal to 200?
if [ $status -ne 200 ]; then
    echo "ERROR: Locus-IR API get location call failed"
    exit 2
fi

echo "OK: Locus-IR get location Checks passed"
